node_type: article
id: 2025-round-1-thunderhill-east-bypass
parent: 2025-86-challenge
title: "2025 Rd 1: Thunderhill East Bypass"
subtitle: 4th in Stock — 2:09.768 adjusted.
content_type: Event
published: false
published_at: null
updated_at: 2026-08-03T22:27:09.643Z
tags:
  - 86-challenge
  - 2025
  - thunderhill
  - east-bypass
media_label: RACE
