node_type: article
id: 2026-round-6-sonoma
parent: 2026-86-challenge
title: "2026 Rd 6: Sonoma"
subtitle: It's not over until it's over.
content_type: Event
published: true
published_at: 2026-10-05T04:36:29.251Z
updated_at: 2026-10-05T04:36:29.251Z
tags:
  - 86-challenge
  - 2026
  - sonoma
media_label: RACE
