node_type: article
id: 2026-round-6-sonoma
parent: 2026-86-challenge
title: "2026 Rd 6: Sonoma"
subtitle: 1st in Stock — 1:57.502 adjusted.
content_type: Event
published: false
published_at: null
updated_at: 2026-08-03T22:27:09.653Z
tags:
  - 86-challenge
  - 2026
  - sonoma
media_label: RACE
