node_type: article
id: 2026-round-8-buttonwillow-1a-ccw
parent: 2026-86-challenge
title: "86Ch Rd8: Buttonwillow CCW1A | Stock Class P1/Record | 2:15.8"
subtitle: Is an understeery car faster if you're not Max Verstappen?
content_type: Event
published: true
published_at: 2026-10-05T19:19:37.074Z
updated_at: 2026-10-05T19:19:38.709Z
tags:
  - 86-challenge
  - 2026
  - buttonwillow
  - 1a-ccw
media_label: RACE
