node_type: article
id: 2026-round-8-buttonwillow-1a-ccw
parent: 2026-86-challenge
title: "2026 Rd 8: Buttonwillow CCW1A"
subtitle: Is an understeery car faster if you're not Max Verstappen?
content_type: Event
published: true
published_at: 2026-09-14T03:00:00.000Z
updated_at: 2026-09-14T03:00:00.000Z
tags:
  - 86-challenge
  - 2026
  - buttonwillow
  - 1a-ccw
media_label: RACE
