node_type: article
id: 2026-round-8-buttonwillow-1a-ccw
parent: 2026-86-challenge
title: "86Ch Rd8: Buttonwillow CCW1A | Stock Class P1/Record | 2:15.8"
subtitle: Event results for Buttonwillow 1A CCW Sun, Sep 13, 2026
content_type: Event
published: false
published_at: null
updated_at: 2026-10-02T00:16:23.577Z
tags:
  - 86-challenge
  - 2026
  - buttonwillow
  - 1a-ccw
media_label: RACE
