node_type: article
id: 2025-round-4-thunderhill-west-ccw
parent: 2025-86-challenge
title: "2025 Rd 4: Thunderhill West CCW"
subtitle: 4th in Stock — 1:30.715 adjusted.
content_type: Event
published: false
published_at: null
updated_at: 2026-08-03T22:27:09.645Z
tags:
  - 86-challenge
  - 2025
  - thunderhill
  - west-ccw
media_label: RACE
