node_type: article
id: before-buying-an-86-brz
parent: blog
title: What do I need to know before buying an 86/BRZ?
subtitle: ''
content_type: Blog
published: false
published_at: null
updated_at: null
tags: [buying, 86, brz]
media_label: BLOG
