node_type: article
id: 2025-round-2-laguna-seca
parent: 2025-86-challenge
title: "2025 Rd 2: Laguna Seca"
subtitle: 3rd in Stock — 1:49.865 adjusted.
content_type: Event
published: false
published_at: null
updated_at: 2026-08-03T22:27:09.646Z
tags:
  - 86-challenge
  - 2025
  - laguna-seca
media_label: RACE
