node_type: article
id: 2026-laguna-seca
parent: 86-challenge
title: '2026 Rd 2: Laguna Seca'
subtitle: Smelling blood
content_type: Event
published: false
published_at: null
updated_at: null
tags: [86-challenge, 2026, laguna-seca]
media_label: RACE
