node_type: article
id: 2026-laguna-seca
parent: 2026-86-challenge
title: "2026 Rd 2: Laguna Seca"
subtitle: Smelling blood
content_type: Event
published: true
published_at: 2026-03-15T03:00:00.000Z
updated_at: 2026-03-15T03:00:00.000Z
tags:
  - 86-challenge
  - 2026
  - laguna-seca
media_label: RACE
