node_type: category
id: 2026-86-challenge
parent: 86-challenge
title: 2026 86 Challenge Season
subtitle: My 3rd year of participating in 86 Challenge, and first time contending for P1.
description: Round records for the 2026 86 Challenge events where Saurabh scored
  points in Stock.
published: true
published_at: 2026-08-03T00:00:00.000Z
updated_at: 2026-10-05T21:13:59.130Z
tags:
  - 86-challenge
  - 2026
media_label: SEASON
