node_type: article
id: 2026-round-7-thunderhill-east-bypass
parent: 2026-86-challenge
title: "2026 Rd 7: Thunderhill East Bypass"
subtitle: Can a "stock" suspension upgrade help me find 1 second?
content_type: Event
published: true
published_at: 2026-06-07T03:00:00.000Z
updated_at: 2026-06-07T03:00:00.000Z
tags:
  - 86-challenge
  - 2026
  - thunderhill
  - east-bypass
media_label: RACE
