node_type: article
id: 2026-round-7-thunderhill-east-bypass
parent: 2026-86-challenge
title: "2026 Rd 7: Thunderhill East Bypass"
subtitle: 2nd in Stock — 2:10.206 adjusted.
content_type: Event
published: false
published_at: null
updated_at: 2026-08-03T22:27:09.654Z
tags:
  - 86-challenge
  - 2026
  - thunderhill
  - east-bypass
media_label: RACE
