node_type: category
id: 86-challenge
title: 86 Challenge
order: 3
description: Event records with onboard video, data and official results.
published: true
updated_at: 2026-08-04T00:16:43.428Z
published_at: 2026-08-04T00:15:43.421Z
