node_type: article
id: 2026-thunderhill-east-cyclone
parent: 2026-86-challenge
title: "2026 Rd 1: Thunderhill East Cyclone"
subtitle: Oversteer, at last
content_type: Event
published: true
published_at: 2026-08-04T00:17:43.442Z
updated_at: 2026-08-04T01:24:34.517Z
tags:
  - 86-challenge
  - 2026
  - thunderhill
media_label: RACE
