node_type: article
id: 2026-thunderhill-east-cyclone
parent: 2026-86-challenge
title: "2026 Rd 1: Thunderhill East Cyclone"
subtitle: Oversteer, at last
content_type: Event
published: true
published_at: 2026-02-15T04:00:00.000Z
updated_at: 2026-02-15T04:00:00.000Z
tags:
  - 86-challenge
  - 2026
  - thunderhill
media_label: RACE
