node_type: article
id: 2025-round-11-sonoma
parent: 2025-86-challenge
title: "2025 Rd 11: Sonoma"
subtitle: 2nd in Stock — 1:58.255 adjusted.
content_type: Event
published: false
published_at: null
updated_at: 2026-08-03T22:27:09.652Z
tags:
  - 86-challenge
  - 2025
  - sonoma
media_label: RACE
